"""Trading-specific Prometheus metrics.

All metrics are module-level singletons registered in the global REGISTRY.
Import this module early in application startup (app.py) to ensure metrics
are registered before the first scrape.

Label conventions:
  broker   — broker adapter name ("kite", "angel", "paper")
  symbol   — underlying instrument ticker
  state    — terminal order/position state value
  reason   — rejection or failure reason bucket
"""

from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram

# ---------------------------------------------------------------------------
# Orders
# ---------------------------------------------------------------------------

ORDERS_SUBMITTED_TOTAL: Counter = Counter(
    "ssa_orders_submitted_total",
    "Total orders submitted to a broker, partitioned by broker and symbol.",
    ["broker", "symbol"],
)

ORDERS_FILLED_TOTAL: Counter = Counter(
    "ssa_orders_filled_total",
    "Total orders confirmed filled by broker.",
    ["broker", "symbol"],
)

ORDERS_FAILED_TOTAL: Counter = Counter(
    "ssa_orders_failed_total",
    "Total order submissions that failed after all retries, partitioned by broker and reason.",
    ["broker", "reason"],
)

ORDERS_CANCELLED_TOTAL: Counter = Counter(
    "ssa_orders_cancelled_total",
    "Total orders cancelled (manual or automatic).",
    ["broker"],
)

ORDERS_RETRIED_TOTAL: Counter = Counter(
    "ssa_orders_retried_total",
    "Total retry attempts for order submission, partitioned by broker.",
    ["broker", "attempt"],
)

# ---------------------------------------------------------------------------
# Signals
# ---------------------------------------------------------------------------

SIGNALS_GENERATED_TOTAL: Counter = Counter(
    "ssa_signals_generated_total",
    "Total trading signals generated by the signal engine.",
    ["strategy_type", "asset_type"],
)

SIGNALS_APPROVED_TOTAL: Counter = Counter(
    "ssa_signals_approved_total",
    "Total signals approved by risk engine.",
    [],
)

SIGNALS_REJECTED_TOTAL: Counter = Counter(
    "ssa_signals_rejected_total",
    "Total signals rejected by risk engine, partitioned by rejection code.",
    ["code"],
)

# ---------------------------------------------------------------------------
# Positions & PnL
# ---------------------------------------------------------------------------

POSITIONS_OPEN: Gauge = Gauge(
    "ssa_positions_open",
    "Current count of open positions.",
    [],
)

PNL_CURRENT_GAUGE: Gauge = Gauge(
    "ssa_pnl_current_inr",
    "Current unrealized + realized PnL for the session, in INR.",
    [],
)

PNL_DAILY_REALIZED: Gauge = Gauge(
    "ssa_pnl_daily_realized_inr",
    "Cumulative realized PnL for the current trading day, in INR.",
    [],
)

# ---------------------------------------------------------------------------
# Broker execution
# ---------------------------------------------------------------------------

BROKER_LATENCY_SECONDS: Histogram = Histogram(
    "ssa_broker_latency_seconds",
    "Latency of broker API calls, partitioned by broker and operation.",
    ["broker", "operation"],
    buckets=(0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
)

BROKER_HEALTH_STATUS: Gauge = Gauge(
    "ssa_broker_health_status",
    "1 if broker is healthy, 0 if degraded/down.",
    ["broker"],
)

BROKER_CONSECUTIVE_FAILURES: Gauge = Gauge(
    "ssa_broker_consecutive_failures",
    "Running count of consecutive broker submission failures.",
    ["broker"],
)

# ---------------------------------------------------------------------------
# Kill switch
# ---------------------------------------------------------------------------

KILL_SWITCH_ACTIVATIONS_TOTAL: Counter = Counter(
    "ssa_kill_switch_activations_total",
    "Total kill switch activations, partitioned by trigger source.",
    ["source"],
)

# ---------------------------------------------------------------------------
# WebSocket
# ---------------------------------------------------------------------------

WEBSOCKET_CONNECTIONS: Gauge = Gauge(
    "ssa_websocket_connections",
    "Current number of active WebSocket client connections.",
    [],
)

WEBSOCKET_MESSAGES_SENT_TOTAL: Counter = Counter(
    "ssa_websocket_messages_sent_total",
    "Total messages broadcast over WebSocket, partitioned by event type.",
    ["event_type"],
)

# ---------------------------------------------------------------------------
# Risk engine
# ---------------------------------------------------------------------------

RISK_EVALUATIONS_TOTAL: Counter = Counter(
    "ssa_risk_evaluations_total",
    "Total risk evaluations performed.",
    [],
)

RISK_REJECTIONS_TOTAL: Counter = Counter(
    "ssa_risk_rejections_total",
    "Total risk evaluations that resulted in rejection.",
    ["code"],
)
