"""Alembic environment — async SQLAlchemy + TimescaleDB aware.

Migration rules from docs/18_TIMESCALEDB_ARCHITECTURE.md:
- TimescaleDB extension must be created before any hypertable.
- create_hypertable() calls use op.execute() — they cannot be autogenerated.
- Continuous aggregates must be dropped before modifying underlying hypertables.
- Never rename hypertable columns in a single migration.
"""

from __future__ import annotations

import asyncio
import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy.ext.asyncio import create_async_engine

# Import Base so autogenerate can detect all models.
from core.infrastructure.database.models import Base  # noqa: F401

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _get_url() -> str:
    url = os.environ.get("DATABASE_WRITE_URL")
    if not url:
        url = config.get_main_option("sqlalchemy.url", "")
    if not url:
        msg = "DATABASE_WRITE_URL environment variable or sqlalchemy.url must be set"
        raise RuntimeError(msg)
    return url


def run_migrations_offline() -> None:
    url = _get_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: object) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)  # type: ignore[arg-type]
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    engine = create_async_engine(_get_url())
    async with engine.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await engine.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
